/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 * Clase que representa la ventana de reglas.
 * Esta ventana muestra las reglas y condiciones del juego en un textarea.
 * Incluye un botón para volver al menú principal.
 * @author edusye
 */
public class Ventana3 extends javax.swing.JFrame {

    /**
     * Constructor de la clase Ventana3.
     * Inicializa todos los componentes de la interfaz gráfica.
     */
    public Ventana3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VOLVER = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VOLVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/Volver.jpg"))); // NOI18N
        VOLVER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VOLVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLVERMouseClicked(evt);
            }
        });
        jPanel1.add(VOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 50, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Colonna MT", 1, 22)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1-Para la formación de una palabra válida, solo se puede utilizar \nuna vez cada elemento (letra) del tablero, es decir, no se puede \nvolver a utilizar un elemento del tablero para la formación \nde la misma palabra. \n\n2-Una palabra válida debe tener al menos 3 letras.\n \n3-Una palabra válida debe existir en un diccionario. \n\n4-No todas las palabras del tablero se encontrarán en el \ndiccionario. \n\n5-Las palabras no llevan acento. \n\n6-Al terminar de seleccionar las letras de la palabra da un\nsegundo click en la ultima letra para confirmar la palabra.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 640, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    /**
     * Maneja el evento de clic del botón VOLVER.
     * Oculta la ventana actual y regresa al menú principal (Ventana1).
     * 
     * @param evt 
    */
    private void VOLVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLVERMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
            Ventana1 v1 = new Ventana1();
            v1.setLocationRelativeTo(null);
            v1.setVisible(true);
    }//GEN-LAST:event_VOLVERMouseClicked

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VOLVER;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
