/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

/**
 * Clase que representa la ventana de selección de partida.
 * Esta ventana permite al usuario elegir entre iniciar una nueva partida o cargar una partida existente.
 * También incluye la opción de volver al menú principal.
 * @author edusye
 */
public class Ventana2 extends javax.swing.JFrame {

    /**
     * Constructor de la clase Ventana2.
     * Inicializa todos los componentes de la interfaz gráfica.
     */
    public Ventana2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VOLVER = new javax.swing.JButton();
        NUEVA1 = new javax.swing.JButton();
        CARGAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VOLVER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Imagenes/Volver.jpg"))); // NOI18N
        VOLVER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VOLVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLVERMouseClicked(evt);
            }
        });
        jPanel1.add(VOLVER, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 50, 50));

        NUEVA1.setBackground(new java.awt.Color(0, 204, 102));
        NUEVA1.setFont(new java.awt.Font("Colonna MT", 1, 48)); // NOI18N
        NUEVA1.setText("CARGAR PARTIDA");
        NUEVA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NUEVA1MouseClicked(evt);
            }
        });
        jPanel1.add(NUEVA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        CARGAR.setBackground(new java.awt.Color(0, 204, 102));
        CARGAR.setFont(new java.awt.Font("Colonna MT", 1, 48)); // NOI18N
        CARGAR.setText("NUEVA PARTIDA");
        CARGAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CARGARMouseClicked(evt);
            }
        });
        jPanel1.add(CARGAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Maneja el evento de clic del botón VOLVER.
     * Oculta la ventana actual y regresa al menú principal (Ventana1).
     * 
     * @param evt 
    */
    private void VOLVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLVERMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Ventana1 v1 = new Ventana1();
        v1.setLocationRelativeTo(null);
        v1.setVisible(true);
    }//GEN-LAST:event_VOLVERMouseClicked
    
    /**
     * Maneja el evento de clic del botón NUEVA PARTIDA.
     * @param evt 
    */  
    private void NUEVA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NUEVA1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_NUEVA1MouseClicked
    
    /**
     * Maneja el evento de clic del botón CARGAR PARTIDA.
     * @param evt
     */
    private void CARGARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CARGARMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CARGARMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CARGAR;
    private javax.swing.JButton NUEVA1;
    private javax.swing.JButton VOLVER;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
