/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Codigo.Tablero;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JPanel;
import org.graphstream.graph.Graph;
import org.graphstream.graph.Node;
import org.graphstream.graph.implementations.SingleGraph;
import org.graphstream.ui.swing_viewer.SwingViewer;
import org.graphstream.ui.view.View;
import org.graphstream.ui.view.Viewer;
/**
 *
 * @author edusye
 */
public class Ventana5 extends javax.swing.JFrame {
    private ArrayList<Integer> camino;

    private Tablero tablero;
    private Graph grafo;
    private Viewer viewer;
    private Ventana4 ventanaPadre;
    
    /**
     * Constructor que recibe el camino, palabra y tablero
     * @param camino
     * @param palabra
     * @param tablero
     * @param ventanaPadre
     */
    public Ventana5(ArrayList<Integer> camino, String palabra, Tablero tablero, Ventana4 ventanaPadre) {
        this.camino = new ArrayList<>(camino);
        this.tablero = tablero;
        
        initComponents();
        crearArbolBFS();
        setLocationRelativeTo(null);
    }
    
    /**
     * Crea el árbol BFS con estructura jerárquica.
     * La raiz es la primera letra seleccionada.
     */
    private void crearArbolBFS() {
        grafo = new SingleGraph("Arbol BFS");
        
        grafo.setAttribute("ui.stylesheet", 
            "node { size: 40px;fill-color: white; text-size: 20px; }");
        
        for (int i = 0; i < camino.size(); i++) {
            char letra = tablero.getLetraCasilla(camino.get(i));
            Node nodo = grafo.addNode("" + i);
            nodo.setAttribute("ui.label", "" + letra);
            
            // Centra en el panel y hace los espacios verticalmente
            double y = (camino.size() / 2.0 - i) * 1.5; 
            nodo.setAttribute("xy", 0, y);
        }
        
        for (int i = 1; i < camino.size(); i++) {
            grafo.addEdge("edge" + i, "" + (i-1), "" + i, true);
        }
        
        viewer = new SwingViewer(grafo, Viewer.ThreadingModel.GRAPH_IN_GUI_THREAD);
        viewer.disableAutoLayout();
        View view = viewer.addDefaultView(false);
        
        JPanel panelView = (JPanel) view;
        panelView.setPreferredSize(new Dimension(640, 385));
        
        ARBOL.removeAll();
        ARBOL.setLayout(new BorderLayout());
        ARBOL.add(panelView, BorderLayout.CENTER);
        ARBOL.revalidate();
        ARBOL.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ARBOL = new javax.swing.JPanel();
        VOLVER = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout ARBOLLayout = new javax.swing.GroupLayout(ARBOL);
        ARBOL.setLayout(ARBOLLayout);
        ARBOLLayout.setHorizontalGroup(
            ARBOLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        ARBOLLayout.setVerticalGroup(
            ARBOLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );

        VOLVER.setBackground(new java.awt.Color(255, 102, 102));
        VOLVER.setFont(new java.awt.Font("Colonna MT", 1, 18)); // NOI18N
        VOLVER.setText("VOLVER");
        VOLVER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        VOLVER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VOLVERMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(VOLVER, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(ARBOL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(ARBOL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(VOLVER)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VOLVERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VOLVERMouseClicked
        // TODO add your handling code here:
        if (ventanaPadre != null) {
            ventanaPadre.setVisible(true);
            ventanaPadre.toFront();
        }
        dispose();
    }//GEN-LAST:event_VOLVERMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ARBOL;
    private javax.swing.JButton VOLVER;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
